from enum import Enum, auto

class Typing(Enum) :
  Jornulo = auto()
  Jormal = auto()
  Jorfogo = auto()
  Jorágua = auto()
  Jorlétrico = auto()
  Jorgrama = auto()
  Jorgelo = auto()
  Jorgutador = auto()
  Jorgenenoso = auto()
  Jorterra = auto()
  Joroador = auto()
  Jorsíquico = auto()
  Jorseto = auto()
  Joredra = auto()
  Jortasma = auto()
  Joragão = auto()
  Jorbrio = auto()
  Jormetal = auto()
  Jorfada = auto()